# Generated by Django 4.0.1 on 2025-10-16 12:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movies/default.jpg', null=True, upload_to=api.models.movie_upload_path),
        ),
    ]
