# Generated by Django 4.0.1 on 2025-10-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('thriller', 'Thriller'), ('romantic', 'Romantic'), ('action', 'Action'), ('comedy', 'Comedy'), ('webseries', 'Web Series'), ('drama', 'Drama')], default='drama', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
